// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/contact.proto

package contactpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TurnstileToken string                 `protobuf:"bytes,4,opt,name=turnstile_token,json=turnstileToken,proto3" json:"turnstile_token,omitempty"`
	RemoteIp       string                 `protobuf:"bytes,5,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContactRequest) Reset() {
	*x = ContactRequest{}
	mi := &file_proto_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequest) ProtoMessage() {}

func (x *ContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequest.ProtoReflect.Descriptor instead.
func (*ContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_proto_rawDescGZIP(), []int{0}
}

func (x *ContactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContactRequest) GetTurnstileToken() string {
	if x != nil {
		return x.TurnstileToken
	}
	return ""
}

func (x *ContactRequest) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

type ContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactResponse) Reset() {
	*x = ContactResponse{}
	mi := &file_proto_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactResponse) ProtoMessage() {}

func (x *ContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactResponse.ProtoReflect.Descriptor instead.
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_proto_rawDescGZIP(), []int{1}
}

func (x *ContactResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_contact_proto protoreflect.FileDescriptor

const file_proto_contact_proto_rawDesc = "" +
	"\n" +
	"\x13proto/contact.proto\x12\tcontactpb\"\x9a\x01\n" +
	"\x0eContactRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12'\n" +
	"\x0fturnstile_token\x18\x04 \x01(\tR\x0eturnstileToken\x12\x1b\n" +
	"\tremote_ip\x18\x05 \x01(\tR\bremoteIp\")\n" +
	"\x0fContactResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2Q\n" +
	"\x0eContactService\x12?\n" +
	"\x06Submit\x12\x19.contactpb.ContactRequest\x1a\x1a.contactpb.ContactResponseB\rZ\v./contactpbb\x06proto3"

var (
	file_proto_contact_proto_rawDescOnce sync.Once
	file_proto_contact_proto_rawDescData []byte
)

func file_proto_contact_proto_rawDescGZIP() []byte {
	file_proto_contact_proto_rawDescOnce.Do(func() {
		file_proto_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_contact_proto_rawDesc), len(file_proto_contact_proto_rawDesc)))
	})
	return file_proto_contact_proto_rawDescData
}

var file_proto_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_contact_proto_goTypes = []any{
	(*ContactRequest)(nil),  // 0: contactpb.ContactRequest
	(*ContactResponse)(nil), // 1: contactpb.ContactResponse
}
var file_proto_contact_proto_depIdxs = []int32{
	0, // 0: contactpb.ContactService.Submit:input_type -> contactpb.ContactRequest
	1, // 1: contactpb.ContactService.Submit:output_type -> contactpb.ContactResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_contact_proto_init() }
func file_proto_contact_proto_init() {
	if File_proto_contact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_contact_proto_rawDesc), len(file_proto_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_contact_proto_goTypes,
		DependencyIndexes: file_proto_contact_proto_depIdxs,
		MessageInfos:      file_proto_contact_proto_msgTypes,
	}.Build()
	File_proto_contact_proto = out.File
	file_proto_contact_proto_goTypes = nil
	file_proto_contact_proto_depIdxs = nil
}
